#
# Generated by generate.py 
#
class VMCompilerInfo:
  def getWordList(self):
    return ["@","c@","!","c!",">r","r>",";","[literal]","[bzero]","[halt]","[nop]","+","nand","2/","0=","[temp]","[codebase]","[dictionary]","cursor!","screen!","keyboard@","blockread@","[stackreset]","blockwrite!"]
  def getDictionaryBase(self):
    return 0x0100
  def getCodeBase(self):
    return 0x1200
  def getBaseLoadAddress(self):
    return 0x0000
